sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - secure: "LCGI81W5DwWMJNYLmNMIKkgz4uIbHeHC2Wg5wHX9E4zDE9yrt4AERzcoa4G9WZ7EJMSkTvYCaYXHO8oYrWX3SSjo/9WEN23LMjJIbVdS7O9BeOTeA3f2NfzE3pdhWahSp5f6lxDYzj+LTyLOrcJGTXnfI8T61Zp6e19bj026jXUCJ1KTXpxFV3fMOWWtSMOMjV6EEbGCH8k9c24XPZ0W/CEPAEAuud3pp+1m3t+IHjJsL304x1v+km4X+6mlMSxPiJZypuAq6hLa4A9M3G5ZLhdumbSr489Dw0fqI4mH9gHKPGFz1gUC1FXPyJUWm80kgR7xer2GzADIQ69Sd+YY7Egt4d1P4ME6pSh11ZMrjfHEtthGP66u571IrQizVQPaOJ6HbWohy+s4574qBhJwYVgQPz97mJGlhJFO/bBg8hFBej1HW5usHkzAPOq0amug25epiMh2R4mPeScVWCajapiDwDKyO50t7/HjV59PTMopXmXpP4XezegrjJwbAyvxSw5pwtW3pMwVSa1yjuqHtvrLTcHOpoNIc6Cm9cqFhT9NlQiklBlXf0SjiFEATluFjDwxjYpAq+kqsPzCBDd/RCZl4ofGaYIJIbxhqLqb5cH4bDfht3hyexvEhLm3HkAFKYuEvkBy8spothDOXSMx+ELN/mrT7eSyXQTGRqu6p+A=" # DOCKER_EMAIL
    - secure: "b+h6IbMntHx1nVO4AONncoJffWv0d3xmfZA1Ddo38ludheZTTM7QvdUGnfts31rE78lwWV43UmXOjO0BhAKqSxJU4TczKZUMQn4BbiwgEjJE3S16cMCrwLhsVgLfTpPJZkPkLVN17MZp0x5sT04ycwM8DV6dFgSJ4DLrEyUhBJnljQhgBhjZq6pJc4/T4FUOcGruNzeJUSO3Q6vZ5ZTxHwgqOBSaBmtSnisQGIOtmAMMlengv/sP1nKFmSfQ4zIRDbXRAj14O5bEoNL6QMUe4NaJh966ki9t19g3Z7r4IOf8cBiwwo0j85V/p/jyNbjP8/p5yOYycZReABkqVVNf6yIqRHp0Af+M9Z3OEDXoBS7K2osK0WFkAxNtI3pOX8118TBIjObB+wvUcr4VooYz1mcTv2O3lvg8Xrxn4uVLPBcDydK3GSs+j9ToQBT3Lj8ZagIJw/f/AlPQAgRCpMaF5OMBdOG0Wr0a7UMiQ34TvmfBcdluZ/VSHE5rV+Fxaf6VRwykddRcGrlRuNKuax9UwP7ttx3p++4Cg3rYinlp2IZU2ku4P4py5nji8dGiI+YAOexi0R7ye8ogM35SrMsVoIorGJ8KYLkrcApV0KeNo2f4saXfT1PX9IJmGdIEt2iemMPKdUZhwLm3SAOyTjNye4lg3IqCksqrm+0Qyhgg5ew=" # DOCKER_USER
    - secure: "mLOqjQp1I3iw4a7ceJXqKLctZy7d1Mdaau3lRcVPx0rli3SUVFTX6ia7KYFFi9Br7XodoTbIb8beX3ifIVfokXjuiArwPdONKTbWKyA0QNiHfMrVjsSN8dXBgLSifjpf5FaHxxcDFe2e9+mUBrkeMXGOuwFTq0/rdYLsuGWbIRx5omvuLKAyuurBbpcRQYwViBtden4peibUrgNVg9YcodT2kgstG/qMy9uoSsdrfBnXJkXwZKa4QiwM3yQ4oEUdrT901zhWrQGegSeuQpSB/BbP2xc4CUZHOz9nQEyd46bzXm2si5qMNIW4iILrjoM5eDYrduKTDRQNuxe/IqDIMHxL7X1umS3zUbN4Xj8kHGRq5OAMBqt4AnjGzFvb3avdK7igrrzB05rDytsHCOw9pbsNpQ66F40x8th+7jZaO6qDsIC0NQQf3zmt0Rm63bcxG6cCy8r3xlgJzwxC9ABr6aM++KoBOeXPGOdIVk1a4fn/8HHc5IJerSAtsdfW/ReQZUz2MNE9w/ws+WmBN1HMWVj2iGcK39yJLclYJ242niJIKDbMa6nBtnhPVQZste+uM+jRSBZpTreFFhHBwI+t/UvCTEjtXJ+nedp8OPJv6bg2Gpp8nQTppZSpPYzd2tXbe7lBMJ8mS09LZZ2tMktJbpIBTth+FPMLyfK9XqMco1Q=" # DOCKER_PASS

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=mrcq/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=mrcq/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=mrcq/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=mrcq/piggymetrics-auth-service
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=mrcq/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # STATISTICS SERVICE
  - export STATISTICS_SERVICE=mrcq/piggymetrics-statistics-service
  - docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # NOTIFICATION_SERVICE
  - export NOTIFICATION_SERVICE=mrcq/piggymetrics-notification-service
  - docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # MONITORING
  - export MONITORING=mrcq/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=mrcq/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=mrcq/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
